grepnumlines: 300
searchbeforecontext: 5
searchaftercontext: 5
tailnumlines: 200
headnumlines: 200

extensions:
  - log

directories:
  - /var/log

logfiles:
#  - /home/user/userlog.log

logfile_glob:
#  - /opt/application/log/newlog-????????.log
