grepnumlines: 250
searchbeforecontext: 2
searchaftercontext: 2

extensions:
 - log

directories:
 - /var/log

logfiles:
 - /home/user/userlog.log

logfile_glob:
 - /opt/application/log/newlog-????????.log